server:
  port: 8090
spring:
  datasource:
    name: zhdjj
    url: jdbc:mysql://localhost:3306/zhdjj?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.zhdjj.demo.pojo
