package com.zhdjj.demo.dao;

import com.zhdjj.demo.pojo.Articlelike;
import com.zhdjj.demo.pojo.ArticlelikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ArticlelikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlelike
     *
     * @mbggenerated
     */
    int countByExample(ArticlelikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlelike
     *
     * @mbggenerated
     */
    int deleteByExample(ArticlelikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlelike
     *
     * @mbggenerated
     */
    int insert(Articlelike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlelike
     *
     * @mbggenerated
     */
    int insertSelective(Articlelike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlelike
     *
     * @mbggenerated
     */
    List<Articlelike> selectByExample(ArticlelikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlelike
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Articlelike record, @Param("example") ArticlelikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlelike
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Articlelike record, @Param("example") ArticlelikeExample example);
}