package com.zhdjj.demo.dao;

import com.zhdjj.demo.pojo.Articlecollection;
import com.zhdjj.demo.pojo.ArticlecollectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ArticlecollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecollection
     *
     * @mbggenerated
     */
    int countByExample(ArticlecollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecollection
     *
     * @mbggenerated
     */
    int deleteByExample(ArticlecollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecollection
     *
     * @mbggenerated
     */
    int insert(Articlecollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecollection
     *
     * @mbggenerated
     */
    int insertSelective(Articlecollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecollection
     *
     * @mbggenerated
     */
    List<Articlecollection> selectByExample(ArticlecollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecollection
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Articlecollection record, @Param("example") ArticlecollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecollection
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Articlecollection record, @Param("example") ArticlecollectionExample example);
}