package com.zhdjj.demo.dao;

import com.zhdjj.demo.pojo.Articlecomment;
import com.zhdjj.demo.pojo.ArticlecommentExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ArticlecommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecomment
     *
     * @mbggenerated
     */
    int countByExample(ArticlecommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecomment
     *
     * @mbggenerated
     */
    int deleteByExample(ArticlecommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecomment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecomment
     *
     * @mbggenerated
     */
    int insert(Articlecomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecomment
     *
     * @mbggenerated
     */
    int insertSelective(Articlecomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecomment
     *
     * @mbggenerated
     */
    List<Articlecomment> selectByExample(ArticlecommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecomment
     *
     * @mbggenerated
     */
    Articlecomment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecomment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Articlecomment record, @Param("example") ArticlecommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecomment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Articlecomment record, @Param("example") ArticlecommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecomment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Articlecomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articlecomment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Articlecomment record);
}