package com.zhdjj.demo.dao;

import com.zhdjj.demo.pojo.Focus;
import com.zhdjj.demo.pojo.FocusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FocusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table focus
     *
     * @mbggenerated
     */
    int countByExample(FocusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table focus
     *
     * @mbggenerated
     */
    int deleteByExample(FocusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table focus
     *
     * @mbggenerated
     */
    int insert(Focus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table focus
     *
     * @mbggenerated
     */
    int insertSelective(Focus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table focus
     *
     * @mbggenerated
     */
    List<Focus> selectByExample(FocusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table focus
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Focus record, @Param("example") FocusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table focus
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Focus record, @Param("example") FocusExample example);
}