package com.zhdjj.demo.dao;

import com.zhdjj.demo.pojo.ShopShopclassfy;
import com.zhdjj.demo.pojo.ShopShopclassfyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ShopShopclassfyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_shopclassfy
     *
     * @mbggenerated
     */
    int countByExample(ShopShopclassfyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_shopclassfy
     *
     * @mbggenerated
     */
    int deleteByExample(ShopShopclassfyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_shopclassfy
     *
     * @mbggenerated
     */
    int insert(ShopShopclassfy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_shopclassfy
     *
     * @mbggenerated
     */
    int insertSelective(ShopShopclassfy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_shopclassfy
     *
     * @mbggenerated
     */
    List<ShopShopclassfy> selectByExample(ShopShopclassfyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_shopclassfy
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ShopShopclassfy record, @Param("example") ShopShopclassfyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_shopclassfy
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ShopShopclassfy record, @Param("example") ShopShopclassfyExample example);
}