package com.zhdjj.demo.dao;

import com.zhdjj.demo.pojo.Shoppingchart;
import com.zhdjj.demo.pojo.ShoppingchartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ShoppingchartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingchart
     *
     * @mbggenerated
     */
    int countByExample(ShoppingchartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingchart
     *
     * @mbggenerated
     */
    int deleteByExample(ShoppingchartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingchart
     *
     * @mbggenerated
     */
    int insert(Shoppingchart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingchart
     *
     * @mbggenerated
     */
    int insertSelective(Shoppingchart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingchart
     *
     * @mbggenerated
     */
    List<Shoppingchart> selectByExample(ShoppingchartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingchart
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Shoppingchart record, @Param("example") ShoppingchartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingchart
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Shoppingchart record, @Param("example") ShoppingchartExample example);
}