package com.zhdjj.demo.dao;

import com.zhdjj.demo.pojo.Shopclassfy;
import com.zhdjj.demo.pojo.ShopclassfyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ShopclassfyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    int countByExample(ShopclassfyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    int deleteByExample(ShopclassfyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer shopclassfyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    int insert(Shopclassfy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    int insertSelective(Shopclassfy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    List<Shopclassfy> selectByExample(ShopclassfyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    Shopclassfy selectByPrimaryKey(Integer shopclassfyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Shopclassfy record, @Param("example") ShopclassfyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Shopclassfy record, @Param("example") ShopclassfyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Shopclassfy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shopclassfy record);
}