package com.zhdjj.demo.dao;

import com.zhdjj.demo.pojo.Tipscomment;
import com.zhdjj.demo.pojo.TipscommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TipscommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscomment
     *
     * @mbggenerated
     */
    int countByExample(TipscommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscomment
     *
     * @mbggenerated
     */
    int deleteByExample(TipscommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscomment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscomment
     *
     * @mbggenerated
     */
    int insert(Tipscomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscomment
     *
     * @mbggenerated
     */
    int insertSelective(Tipscomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscomment
     *
     * @mbggenerated
     */
    List<Tipscomment> selectByExample(TipscommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscomment
     *
     * @mbggenerated
     */
    Tipscomment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscomment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tipscomment record, @Param("example") TipscommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscomment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tipscomment record, @Param("example") TipscommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscomment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tipscomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscomment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tipscomment record);
}