package com.zhdjj.demo.dao;

import com.zhdjj.demo.pojo.Tips;
import com.zhdjj.demo.pojo.TipsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TipsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tips
     *
     * @mbggenerated
     */
    int countByExample(TipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tips
     *
     * @mbggenerated
     */
    int deleteByExample(TipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tips
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tips
     *
     * @mbggenerated
     */
    int insert(Tips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tips
     *
     * @mbggenerated
     */
    int insertSelective(Tips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tips
     *
     * @mbggenerated
     */
    List<Tips> selectByExample(TipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tips
     *
     * @mbggenerated
     */
    Tips selectByPrimaryKey(Integer tipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tips
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tips record, @Param("example") TipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tips
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tips record, @Param("example") TipsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tips
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tips
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tips record);
}