package com.zhdjj.demo.dao;

import com.zhdjj.demo.pojo.Tipscollection;
import com.zhdjj.demo.pojo.TipscollectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TipscollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscollection
     *
     * @mbggenerated
     */
    int countByExample(TipscollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscollection
     *
     * @mbggenerated
     */
    int deleteByExample(TipscollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscollection
     *
     * @mbggenerated
     */
    int insert(Tipscollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscollection
     *
     * @mbggenerated
     */
    int insertSelective(Tipscollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscollection
     *
     * @mbggenerated
     */
    List<Tipscollection> selectByExample(TipscollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscollection
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tipscollection record, @Param("example") TipscollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscollection
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tipscollection record, @Param("example") TipscollectionExample example);
}