package com.zhdjj.demo.pojo;

import java.io.Serializable;

public class Article implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_id
     *
     * @mbggenerated
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author_id
     *
     * @mbggenerated
     */
    private Integer authorId;
    private Author author;

    public Author getAuthor() {
        return author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }

    public Shop getShop() {
        return shop;
    }

    public void setShop(Shop shop) {
        this.shop = shop;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_name
     *
     * @mbggenerated
     */
    private String articleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_content
     *
     * @mbggenerated
     */
    private String articleContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_classfy
     *
     * @mbggenerated
     */
    private Integer articleClassfy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_shop
     *
     * @mbggenerated
     */
    private Integer articleShop;
    private Shop shop;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_id
     *
     * @return the value of article.article_id
     *
     * @mbggenerated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_id
     *
     * @param articleId the value for article.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author_id
     *
     * @return the value of article.author_id
     *
     * @mbggenerated
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.author_id
     *
     * @param authorId the value for article.author_id
     *
     * @mbggenerated
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_name
     *
     * @return the value of article.article_name
     *
     * @mbggenerated
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_name
     *
     * @param articleName the value for article.article_name
     *
     * @mbggenerated
     */
    public void setArticleName(String articleName) {
        this.articleName = articleName == null ? null : articleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_content
     *
     * @return the value of article.article_content
     *
     * @mbggenerated
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_content
     *
     * @param articleContent the value for article.article_content
     *
     * @mbggenerated
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_classfy
     *
     * @return the value of article.article_classfy
     *
     * @mbggenerated
     */
    public Integer getArticleClassfy() {
        return articleClassfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_classfy
     *
     * @param articleClassfy the value for article.article_classfy
     *
     * @mbggenerated
     */
    public void setArticleClassfy(Integer articleClassfy) {
        this.articleClassfy = articleClassfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_shop
     *
     * @return the value of article.article_shop
     *
     * @mbggenerated
     */
    public Integer getArticleShop() {
        return articleShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_shop
     *
     * @param articleShop the value for article.article_shop
     *
     * @mbggenerated
     */
    public void setArticleShop(Integer articleShop) {
        this.articleShop = articleShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleId=").append(articleId);
        sb.append(", authorId=").append(authorId);
        sb.append(", articleName=").append(articleName);
        sb.append(", articleContent=").append(articleContent);
        sb.append(", articleClassfy=").append(articleClassfy);
        sb.append(", articleShop=").append(articleShop);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}