package com.zhdjj.demo.pojo;

import java.io.Serializable;

public class ArticleArticleclassfy implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_articleclassfy.article_id
     *
     * @mbggenerated
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_articleclassfy.article_classfy_id
     *
     * @mbggenerated
     */
    private Integer articleClassfyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_articleclassfy
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_articleclassfy.article_id
     *
     * @return the value of article_articleclassfy.article_id
     *
     * @mbggenerated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_articleclassfy.article_id
     *
     * @param articleId the value for article_articleclassfy.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_articleclassfy.article_classfy_id
     *
     * @return the value of article_articleclassfy.article_classfy_id
     *
     * @mbggenerated
     */
    public Integer getArticleClassfyId() {
        return articleClassfyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_articleclassfy.article_classfy_id
     *
     * @param articleClassfyId the value for article_articleclassfy.article_classfy_id
     *
     * @mbggenerated
     */
    public void setArticleClassfyId(Integer articleClassfyId) {
        this.articleClassfyId = articleClassfyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_articleclassfy
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleId=").append(articleId);
        sb.append(", articleClassfyId=").append(articleClassfyId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}