package com.zhdjj.demo.pojo;

import java.io.Serializable;

public class Articleclassfy implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleclassfy.article_classfy_id
     *
     * @mbggenerated
     */
    private Integer articleClassfyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleclassfy.article_classfy_name
     *
     * @mbggenerated
     */
    private String articleClassfyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table articleclassfy
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleclassfy.article_classfy_id
     *
     * @return the value of articleclassfy.article_classfy_id
     *
     * @mbggenerated
     */
    public Integer getArticleClassfyId() {
        return articleClassfyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleclassfy.article_classfy_id
     *
     * @param articleClassfyId the value for articleclassfy.article_classfy_id
     *
     * @mbggenerated
     */
    public void setArticleClassfyId(Integer articleClassfyId) {
        this.articleClassfyId = articleClassfyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleclassfy.article_classfy_name
     *
     * @return the value of articleclassfy.article_classfy_name
     *
     * @mbggenerated
     */
    public String getArticleClassfyName() {
        return articleClassfyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleclassfy.article_classfy_name
     *
     * @param articleClassfyName the value for articleclassfy.article_classfy_name
     *
     * @mbggenerated
     */
    public void setArticleClassfyName(String articleClassfyName) {
        this.articleClassfyName = articleClassfyName == null ? null : articleClassfyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleclassfy
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleClassfyId=").append(articleClassfyId);
        sb.append(", articleClassfyName=").append(articleClassfyName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}