package com.zhdjj.demo.pojo;

import java.io.Serializable;

public class Focus implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column focus.user_id
     *
     * @mbggenerated
     */
    private Integer userId;
    private Users users;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column focus.focus_id
     *
     * @mbggenerated
     */
    private Integer focusId;
    private Users focus;

    public Users getUsers() {
        return users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public Users getFocus() {
        return focus;
    }

    public void setFocus(Users focus) {
        this.focus = focus;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table focus
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column focus.user_id
     *
     * @return the value of focus.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column focus.user_id
     *
     * @param userId the value for focus.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column focus.focus_id
     *
     * @return the value of focus.focus_id
     *
     * @mbggenerated
     */
    public Integer getFocusId() {
        return focusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column focus.focus_id
     *
     * @param focusId the value for focus.focus_id
     *
     * @mbggenerated
     */
    public void setFocusId(Integer focusId) {
        this.focusId = focusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table focus
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", focusId=").append(focusId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}