package com.zhdjj.demo.pojo;

import java.io.Serializable;

public class Notice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_id
     *
     * @mbggenerated
     */
    private Integer noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.users_id
     *
     * @mbggenerated
     */
    private Integer usersId;
    private Users users;

    public Users getUsers() {
        return users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_content
     *
     * @mbggenerated
     */
    private String noticeContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_status
     *
     * @mbggenerated
     */
    private Byte noticeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notice
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_id
     *
     * @return the value of notice.notice_id
     *
     * @mbggenerated
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_id
     *
     * @param noticeId the value for notice.notice_id
     *
     * @mbggenerated
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.users_id
     *
     * @return the value of notice.users_id
     *
     * @mbggenerated
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.users_id
     *
     * @param usersId the value for notice.users_id
     *
     * @mbggenerated
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_content
     *
     * @return the value of notice.notice_content
     *
     * @mbggenerated
     */
    public String getNoticeContent() {
        return noticeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_content
     *
     * @param noticeContent the value for notice.notice_content
     *
     * @mbggenerated
     */
    public void setNoticeContent(String noticeContent) {
        this.noticeContent = noticeContent == null ? null : noticeContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_status
     *
     * @return the value of notice.notice_status
     *
     * @mbggenerated
     */
    public Byte getNoticeStatus() {
        return noticeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_status
     *
     * @param noticeStatus the value for notice.notice_status
     *
     * @mbggenerated
     */
    public void setNoticeStatus(Byte noticeStatus) {
        this.noticeStatus = noticeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", noticeId=").append(noticeId);
        sb.append(", usersId=").append(usersId);
        sb.append(", noticeContent=").append(noticeContent);
        sb.append(", noticeStatus=").append(noticeStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}