package com.zhdjj.demo.pojo;

import java.util.ArrayList;
import java.util.List;

public class ShopclassfyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    public ShopclassfyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShopclassfyIdIsNull() {
            addCriterion("shopclassfy_id is null");
            return (Criteria) this;
        }

        public Criteria andShopclassfyIdIsNotNull() {
            addCriterion("shopclassfy_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopclassfyIdEqualTo(Integer value) {
            addCriterion("shopclassfy_id =", value, "shopclassfyId");
            return (Criteria) this;
        }

        public Criteria andShopclassfyIdNotEqualTo(Integer value) {
            addCriterion("shopclassfy_id <>", value, "shopclassfyId");
            return (Criteria) this;
        }

        public Criteria andShopclassfyIdGreaterThan(Integer value) {
            addCriterion("shopclassfy_id >", value, "shopclassfyId");
            return (Criteria) this;
        }

        public Criteria andShopclassfyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopclassfy_id >=", value, "shopclassfyId");
            return (Criteria) this;
        }

        public Criteria andShopclassfyIdLessThan(Integer value) {
            addCriterion("shopclassfy_id <", value, "shopclassfyId");
            return (Criteria) this;
        }

        public Criteria andShopclassfyIdLessThanOrEqualTo(Integer value) {
            addCriterion("shopclassfy_id <=", value, "shopclassfyId");
            return (Criteria) this;
        }

        public Criteria andShopclassfyIdIn(List<Integer> values) {
            addCriterion("shopclassfy_id in", values, "shopclassfyId");
            return (Criteria) this;
        }

        public Criteria andShopclassfyIdNotIn(List<Integer> values) {
            addCriterion("shopclassfy_id not in", values, "shopclassfyId");
            return (Criteria) this;
        }

        public Criteria andShopclassfyIdBetween(Integer value1, Integer value2) {
            addCriterion("shopclassfy_id between", value1, value2, "shopclassfyId");
            return (Criteria) this;
        }

        public Criteria andShopclassfyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shopclassfy_id not between", value1, value2, "shopclassfyId");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameIsNull() {
            addCriterion("shopclassfy_name is null");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameIsNotNull() {
            addCriterion("shopclassfy_name is not null");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameEqualTo(String value) {
            addCriterion("shopclassfy_name =", value, "shopclassfyName");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameNotEqualTo(String value) {
            addCriterion("shopclassfy_name <>", value, "shopclassfyName");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameGreaterThan(String value) {
            addCriterion("shopclassfy_name >", value, "shopclassfyName");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameGreaterThanOrEqualTo(String value) {
            addCriterion("shopclassfy_name >=", value, "shopclassfyName");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameLessThan(String value) {
            addCriterion("shopclassfy_name <", value, "shopclassfyName");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameLessThanOrEqualTo(String value) {
            addCriterion("shopclassfy_name <=", value, "shopclassfyName");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameLike(String value) {
            addCriterion("shopclassfy_name like", value, "shopclassfyName");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameNotLike(String value) {
            addCriterion("shopclassfy_name not like", value, "shopclassfyName");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameIn(List<String> values) {
            addCriterion("shopclassfy_name in", values, "shopclassfyName");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameNotIn(List<String> values) {
            addCriterion("shopclassfy_name not in", values, "shopclassfyName");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameBetween(String value1, String value2) {
            addCriterion("shopclassfy_name between", value1, value2, "shopclassfyName");
            return (Criteria) this;
        }

        public Criteria andShopclassfyNameNotBetween(String value1, String value2) {
            addCriterion("shopclassfy_name not between", value1, value2, "shopclassfyName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shopclassfy
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}