package com.zhdjj.demo.pojo;

import java.io.Serializable;

public class Shopclassfy implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopclassfy.shopclassfy_id
     *
     * @mbggenerated
     */
    private Integer shopclassfyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopclassfy.shopclassfy_name
     *
     * @mbggenerated
     */
    private String shopclassfyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopclassfy.shopclassfy_id
     *
     * @return the value of shopclassfy.shopclassfy_id
     *
     * @mbggenerated
     */
    public Integer getShopclassfyId() {
        return shopclassfyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopclassfy.shopclassfy_id
     *
     * @param shopclassfyId the value for shopclassfy.shopclassfy_id
     *
     * @mbggenerated
     */
    public void setShopclassfyId(Integer shopclassfyId) {
        this.shopclassfyId = shopclassfyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopclassfy.shopclassfy_name
     *
     * @return the value of shopclassfy.shopclassfy_name
     *
     * @mbggenerated
     */
    public String getShopclassfyName() {
        return shopclassfyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopclassfy.shopclassfy_name
     *
     * @param shopclassfyName the value for shopclassfy.shopclassfy_name
     *
     * @mbggenerated
     */
    public void setShopclassfyName(String shopclassfyName) {
        this.shopclassfyName = shopclassfyName == null ? null : shopclassfyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopclassfy
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shopclassfyId=").append(shopclassfyId);
        sb.append(", shopclassfyName=").append(shopclassfyName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}