package com.zhdjj.demo.pojo;

import java.io.Serializable;

public class Tips implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tips.tip_id
     *
     * @mbggenerated
     */
    private Integer tipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tips.user_id
     *
     * @mbggenerated
     */
    private Integer userId;
    private Users users;

    public Users getUsers() {
        return users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tips.tip_name
     *
     * @mbggenerated
     */
    private String tipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tips.tip_content
     *
     * @mbggenerated
     */
    private String tipContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tips
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tips.tip_id
     *
     * @return the value of tips.tip_id
     *
     * @mbggenerated
     */
    public Integer getTipId() {
        return tipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tips.tip_id
     *
     * @param tipId the value for tips.tip_id
     *
     * @mbggenerated
     */
    public void setTipId(Integer tipId) {
        this.tipId = tipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tips.user_id
     *
     * @return the value of tips.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tips.user_id
     *
     * @param userId the value for tips.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tips.tip_name
     *
     * @return the value of tips.tip_name
     *
     * @mbggenerated
     */
    public String getTipName() {
        return tipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tips.tip_name
     *
     * @param tipName the value for tips.tip_name
     *
     * @mbggenerated
     */
    public void setTipName(String tipName) {
        this.tipName = tipName == null ? null : tipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tips.tip_content
     *
     * @return the value of tips.tip_content
     *
     * @mbggenerated
     */
    public String getTipContent() {
        return tipContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tips.tip_content
     *
     * @param tipContent the value for tips.tip_content
     *
     * @mbggenerated
     */
    public void setTipContent(String tipContent) {
        this.tipContent = tipContent == null ? null : tipContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tips
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tipId=").append(tipId);
        sb.append(", userId=").append(userId);
        sb.append(", tipName=").append(tipName);
        sb.append(", tipContent=").append(tipContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}