package com.zhdjj.demo.pojo;

import java.io.Serializable;

public class Tipslike implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipslike.tip_id
     *
     * @mbggenerated
     */
    private Integer tipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipslike.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tipslike
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipslike.tip_id
     *
     * @return the value of tipslike.tip_id
     *
     * @mbggenerated
     */
    public Integer getTipId() {
        return tipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipslike.tip_id
     *
     * @param tipId the value for tipslike.tip_id
     *
     * @mbggenerated
     */
    public void setTipId(Integer tipId) {
        this.tipId = tipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipslike.user_id
     *
     * @return the value of tipslike.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipslike.user_id
     *
     * @param userId the value for tipslike.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipslike
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tipId=").append(tipId);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}