package com.zhdjj.demo.pojo;

import java.io.Serializable;

public class Tipscomment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipscomment.comment_id
     *
     * @mbggenerated
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipscomment.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipscomment.tip_id
     *
     * @mbggenerated
     */
    private Integer tipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipscomment.comment_content
     *
     * @mbggenerated
     */
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tipscomment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipscomment.comment_id
     *
     * @return the value of tipscomment.comment_id
     *
     * @mbggenerated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipscomment.comment_id
     *
     * @param commentId the value for tipscomment.comment_id
     *
     * @mbggenerated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipscomment.user_id
     *
     * @return the value of tipscomment.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipscomment.user_id
     *
     * @param userId the value for tipscomment.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipscomment.tip_id
     *
     * @return the value of tipscomment.tip_id
     *
     * @mbggenerated
     */
    public Integer getTipId() {
        return tipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipscomment.tip_id
     *
     * @param tipId the value for tipscomment.tip_id
     *
     * @mbggenerated
     */
    public void setTipId(Integer tipId) {
        this.tipId = tipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipscomment.comment_content
     *
     * @return the value of tipscomment.comment_content
     *
     * @mbggenerated
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipscomment.comment_content
     *
     * @param commentContent the value for tipscomment.comment_content
     *
     * @mbggenerated
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipscomment
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commentId=").append(commentId);
        sb.append(", userId=").append(userId);
        sb.append(", tipId=").append(tipId);
        sb.append(", commentContent=").append(commentContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}